services:
  # MongoDB for document metadata
  mongodb:
    image: mongo:6.0
    container_name: ask2slide-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ask2slide_admin
      - MONGO_INITDB_ROOT_PASSWORD=s3cur3P@ssw0rd
    restart: unless-stopped

  # MinIO for document storage
  minio:
    image: quay.io/minio/minio:RELEASE.2023-07-21T21-12-44Z
    container_name: ask2slide-minio
    ports:
      - "9010:9000"  # API
      - "9011:9001"  # Console
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=ask2slide_minio
      - MINIO_ROOT_PASSWORD=m1n10P@ssw0rd
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  mongodb_data:
  minio_data:
